import * as vscode from 'vscode';

const EXTENSION_ID = "levybajamundi.ui5-ts-codegen";

export enum AutoGenType {
    model,
    control
}

export default class Util {
    /**
     * Converts string to camel case ("hello" => "Hello"; "helloWorld" => "HelloWorld")
     * @param {*} str
     */
    public static toCamelCase(str:string) {
        return str.charAt(0).toUpperCase() + str.substr(1);
    }

    /**
     * Returns the number of occurrences of word in origStr.
     * @param origStr 
     * @param word 
     */
    public static countOccurrences(origStr:string, word:string) {
        return origStr.split(word).length - 1;
    }

    /**
     * Returns a message that is intended to be placed as part of the autogenerated jsdoc.
     * @returns 
     */
    public static getAutoGenMessage(className:string, type:AutoGenType = AutoGenType.model) {
        let message = "";
        let version = vscode.extensions.getExtension(EXTENSION_ID)?.packageJSON.version;

        message += `//-----------------------------------------------------------------------------------\n`;
        if ( type === AutoGenType.model) {
            message += `// Auto generated functions based from ${className} for use in OpenUI5 \n`;
            message += `// views and controllers. \n`;
        } else {
            message += `// Auto generated functions of ${className} based on metadata definition \n`;
        }
        message += `//\n`;
        message += `// Generated using {@link https://github.com/tapsiturbi/ui5-ts-codegen} version ${version} \n`;
        message += `// on ${new Date().toString()} \n`;
        message += `//-----------------------------------------------------------------------------------\n\n`;

        return message;
    }

    /**
     * If str starts with any of the strings from the list, returns the substring of str
     * excluding the match
     */
    public static getTrimmedFromStart(str:string, searchList:string[]) : string | null {
        for(const search of searchList) {
            if ( str.startsWith(search) ) {
                return str.substr(search.length);
            }
        }

        return null;
    }

    /**
     * Hardcoded check for the root classes of UI5
     * @param className 
     */
    public static isRootUI5Class(className:string) {
        return ["sap.ui.core.Element", "sap.ui.base.ManagedObject", "sap.ui.base.EventProvider", "sap.ui.base.Object"].indexOf(className) > -1;
    }
}